### ISSUE TITLE
Please add DigitalStakeout

### ISSUE THREAD

**Issue by amikrut** [jivoi/awesome-osint#128]
Awesome list!

Please add Digitalstakeout to the list. 
https://www.digitalstakeout.com/platform

Social Media Tools
Real-Time Search, Social Media Search, and General Social Media Tools
Domain and IP Research
Threat Intelligence

Suggested Categories:
Dark Web Monitoring
Dark Web Search Engines

**Comment by spmedia** [comment]
Added #135. Thank you.
