### ISSUE TITLE
Link to ExtractFace leads to 404

### ISSUE THREAD

**Issue by Ullaakut** [jivoi/awesome-osint#134]
[Here is the link](http://le-tools.com/ExtractFace.html#download), found in the [README of this repo at line 351](https://github.com/jivoi/awesome-osint/blob/master/README.md#L351).

AFAIK, its name changed last year from ExtractFace to [DumpItBlue](https://le-tools.com/DumpItBlue.html) but I might be wrong so I don't want to open a PR myself that might be based on a misunderstanding.

**Comment by spmedia** [comment]
Awesome find, thank you! Updated #135.
