### ISSUE TITLE
Mistake about an accronyme

### ISSUE THREAD

**Issue by clement961** [jivoi/awesome-osint#149]
Hello. I found a mistake about the AFP acronym in the "News" section of the list. AFP doesn't mean "Associated France Press", but "Agence France-Presse". Apparently, the name isn't translated into english (https://en.wikipedia.org/wiki/Agence_France-Presse). I think there was a confusion with the AP (Associated Press) which is another agency.

**Comment by spmedia** [comment]
Thank you.

Fixed in #166. :)
