### ISSUE TITLE
Consider adding analyzeid

### ISSUE THREAD

**Issue by itsdai** [jivoi/awesome-osint#150]
Can you consider adding analyzeid to the list?
https://analyzeid.com/

Search for other websites owned by the same person using reverse lookup Google Adsense & Google Analytics.

Category: Domain and IP Research

Non-related:
These websites seem to be down. I don't want to do a PR if these sites are temporarily down.

https://unicorns.io/
Unicorns

http://sameid.net/
SameID

http://www.tweetpaths.com/
Tweetpaths

**Comment by spmedia** [comment]
Thank you.

Fixed in #166. :)
