### ISSUE TITLE
Add Pastebin alternatives? 

### ISSUE THREAD

**Issue by researchsmith** [jivoi/awesome-osint#158]
The search function was removed from Pastebin but most of these sites still have search functions. 
Alternatively TrashPanda is a good scraper for most bin sites: https://twitter.com/leak_scavenger by @rnd_infosec_guy

https://batman.gyptis.org/zerobin 
https://Cl1p.net 
https://Codepad.org 
https://Controlc.com 
https://Doxbin.org 
https://Dpaste.com 
https://Dpaste.org 
https://Dumpz.org 
https://Friendpast.com 
https://ghostbin.co/
https://Gist.github.com 
https://Hastebin.com 
https://Heypasteit.com 
https://Hpaste.org 
https://Ideone.com 
https://Ivpaste.com 
https://Jsbin.com 
https://Justpaste.it 
https://Mysticpaste.com 
https://Nopaste.info 
https://0bin.net 
https://Obin.net 
https://Paste.debian.net 
https://Paste.ee 
https://Paste.fedoraproject.org 
https://Paste.frubar.net 
https://Paste.kde.org 
https://Paste.lisp.org 
https://Paste.pound-python.org 
https://Paste.openuse.org 
http://doxbinjs77uawbbl.onion/ (Tor bin site)

**Comment by spmedia** [comment]
Thank you.

Added in #166. :)
