### ISSUE TITLE
New service for "E-mail Search / E-mail Check" category

### ISSUE THREAD

**Issue by LeakCheck** [jivoi/awesome-osint#172]
Hi, I would like to add our service into "E-mail Search / E-mail Check" category. We have been working for 2.5 years, since this period we've collected about 7.5B entries from more than 3000 databases and this number is still growing. We provide API on any subscription (SLA 99.95%), integration with Telegram bot, notifications of new entries and allow search by e-mail, username, password, corporate domain name, hash. Officially registered as a company, using reliable hosting and payment providers.
Our website: https://leakcheck.net

**Comment by spmedia** [comment]
Just submit a PR and its fine.
