### ISSUE TITLE
People Investigations Links Reviewed

### ISSUE THREAD

**Issue by rbarosky** [jivoi/awesome-osint#176]
- 1st section - links to remove, including notes.
- 2nd section - links to keep, including updated descriptions.

--------------------------------------------------

* [Alumni.net](http://www.alumni.net) - Should remove. It's a job search site. The members/discussion area looks to be abandoned, with the most recent discussions being from 2018.
* [Charlie App](https://charlieapp.com) - Should remove. All data behind paywall. Looks to be sales-focused data.
* [Cedar](http://www.cedar.buffalo.edu/AdServ/person-search.html) - Should remove. Only an affiliate funnel to whitepages.com. Doesn't even proxy search query to affiliate site.
* [CVGadget](http://www.cvgadget.com) - Remove. No value results. Simply proxies to Google web, images, documents, blogs, and news results.
* [Data 24-7](https://www.data24-7.com) - Remove since not OSINT. API-driven name, phone, and email searches. Premium service and data only.
* [Family Tree Now](http://www.familytreenow.com/) - Remove. Site is only an affiliate funnel to truepeoplesearch.com and peoplefinders.com, which only offers premium upsell reports.
* [Hey Press (Search for Journalists)](https://www.hey.press) - Remove. Website dead.
* [Infobel](http://www.infobel.com/en/world) - Remove. Functionality broken. Most directry dropdown links are broken.
* [Interment](http://www.interment.net/data/search.htm) - Remove. Low/no value. Only proxies to Google web results.
* [International White and Yellow Pages](http://www.wayp.com) - Remove. Site is only an affiliate funnel to whitepages.com.
* [Itools](http://itools.com/search/people-search) - Remove. Site is only an affiliate funnel. (Spokeo, whitepages.com, etc.)
* [LookUpUK](http://www.lookupuk.com) - Remove. Site is only an affiliate funnel. (ancestry.com, 192.com, etc)
* [Lullar](http://com.lullar.com) - Remove. Low/no value results. No value added. Proxies to 30 URLs with query parameter from search input embedded in generated URLs. Not maintained. Generated URLs don't even create valid search queries in multiple cases tested.
* [MarketVisual](http://www.marketvisual.com) - Remove. Site dead.
* [MelissaDATA](http://www.melissadata.com/lookups/peoplefinder.asp) - Remove. Not OSINT.  Premium data and services only.
* [PeopleSearch.net](http://www.peoplesearch.net) - Remove. Very low value directory site. Limited actual info and many affiliate search ads and affiliate links.
* [Pipl](https://pipl.com) - Remove. Not OSINT. Premium search services only. 
* [Rapportive](http://rapportive.com) - Remove Not OSINT. Premium data product bought by LinkedIn.
* [RecordsPedia](http://recordspedia.com) - Remove. Low/no value website. Broken with errors. Used to be thin affiliate funnel site most likely.
* [Recruitem](http://recruitin.net) - Remove. Only proxies to Google search results for LinkedIn, Github, StackOverflow, etc. results. No value added.
* [Rootsweb](http://home.rootsweb.ancestry.com) - Probably remove, since it's part of ancestry.com, which is already linked.
* [Skip Ease](http://www.skipease.com) - Remove. Thin affiliate funnel site.
* [Smart Background Checks](https://www.smartbackgroundchecks.com/people/) - Remove. Thin affiliate funnel site to beenverified.com.
* [snitch.name](http://www.snitch.name) - Remove. Functionality broken. Searching results in the download of an aspx file.
* [SnoopStation](http://snoopstation.com) - Remove. Affiliate funnel site to Intelius.
* [Switchboard](http://www.switchboard.com) - Remove. Affiliate funnel site to whitepages.com.
* [That’sThem](https://thatsthem.com) - Remove. Affiliate funnel site to instantcheckmate.com
* [USSearch](http://www.ussearch.com) - Remove. Affiliate funnel site only.
* [WebMiii](http://www.webmii.com) - Remove. Low/no value results. Looks like a Spokeo attempt from a high school computer class.
* [Wink](http://itools.com/tool/wink-people-search) - Remove. Broken search goes to 404 page.
* [Yasni](http://www.yasni.com) - Remove. Extremely low value site. Looks like 10+ years since last update. Other sites like LinkedIn, Google, and free Spokeo info are much better.
* [Zabasearch](http://www.zabasearch.com) - Remove. Affiliate funnel site to Intelius.
* [Zoominfo](http://www.zoominfo.com) - Remove Not OSINT. Premium search/data services only.
* [PeekYou](http://www.peekyou.com) - Another affiliate funnel site.
* [People Search (Australia)](http://www.peoplesearch.com.au) - Low/no value. Site not maintained. Main search box function in header results in 404. Many low value affiliate links among a few useful links.

--------------------------------------------------

* [411 (US)](http://www.411.com) - Search by person, phone number, address, and business. Limited free info, premium data upsell.
* [192 (UK)](http://www.192.com) - Search by person, business, address. Limited free info, premium data upsell.
* [Ancestry](http://www.ancestry.com) - Premium data, free trial with credit card.
* [Canada411](http://www.canada411.ca) - Search by person, phone number, and business. Free.
* [Classmates](http://www.classmates.com) - High-school focused people search. Free acounts allow creating a profile and viewing other members. Premium account required to contact other members.
* [CrunchBase](http://www.crunchbase.com) - Business information database, with a focus on investment, acquisition, and executive data. Ancillary focus on market research and connecting founders and investors.
* [facesearch](http://facesaerch.com) - Handy proxy to search Google face-only image search results.
* [Family Search](https://familysearch.org) - Popular genealogy site. Free, but registration requried. Funded by The Church Of Jesus Christ of Latter-day Saints.
* [Federal Bureau of Prisons - Inmate Locator (US)](http://www.bop.gov/inmateloc) - Search federal inmates incarcerated from 1982 to the present. 
* [Fold3 (US Military Records)](http://www.fold3.com) - Search military records. Search filters limited with free access. Premium access requires subscription.
* [Genealogy Bank](http://www.genealogybank.com) - Premium data, free trial with credit card.
* [Genealogy Links](http://www.genealogylinks.net) - Genealogy directory with over 50K links.
* [Homemetry](https://homemetry.com) - Reverse address search and allows searching for properties for sale/rent.
* [Kompass](http://www.kompass.com) - Business directory and search.
* [My Life People Search](https://www.mylife.com/people-search) - People search. Limited free info, premium data upsell.
* [The National Archives (UK)](http://www.nationalarchives.gov.uk) - Search UK national archives.
* [Reunion](http://reunion.com) - People search. Limited free info, premium data upsell.
* [SearchBug](http://www.searchbug.com) - People search. Limited free info, premium data upsell.
* [Spokeo](http://www.spokeo.com) - People search. Limited free info, premium data upsell.
* [White Pages (US)](http://www.whitepages.com) - People search. Limited free info, premium data upsell.
* [Black Book Online](https://www.blackbookonline.info) - Free. Nationwide directory of public record lookups.
* [Judyrecords](https://www.judyrecords.com/) - Free. Nationwide search of 400 million+ United States court cases.
* [UniCourt](https://unicourt.com/) - Limited free searches, premium data upsell. Nationwide search of 100 million+ United States court cases.

--------------------------------------------------

Add to company research section:
- JudyRecords - Free. Nationwide search of 400 million+ United States court cases.
- UniCourt - Limited free searches, premium data upsell. Nationwide search of 100 million+ United States court cases.

**Comment by rbarosky** [comment]
PR for these changes here:
https://github.com/jivoi/awesome-osint/pull/177

**Comment by spmedia** [comment]
merged into master
