### ISSUE TITLE
adding another social searcher

### ISSUE THREAD

**Issue by Likahler** [jivoi/awesome-osint#190]
I saw your page:
https://github.com/jivoi/awesome-osint

Could you please add our tool there as well, in exchange for free notifier account?
<img width="389" alt="image" src="https://user-images.githubusercontent.com/26372378/101686247-69a10900-3a2e-11eb-9214-cc098d4db44b.png">

Our tool:
https://notifierforreddit.com

**Comment by spmedia** [comment]
No
