### ISSUE TITLE
Do not add pirated content Maigret. ban https://github.com/jivoi/awesome-osint/pull/199

### ISSUE THREAD

**Issue by snooppr** [jivoi/awesome-osint#201]
This repository has violated the copyright of the Snoop Project https://github.com/snooppr/snoop.
An attacker illegally used the 'BDfull' Snoop database. At the moment, the pirate was blocked on Gitlab (for this case https://gitlab.com/soxoj), I will also recover from him for copyright infringement, so that Github would react.
You can check the post https://github.com/BlackArch/blackarch/issues/2848#issuecomment-739153757

After restoring the maigret repository (Soxoj began cleaning up its traces, deleting all its commits). But Github has an api that shows the real history of the maigret repository https://api.github.com/repos/soxoj/maigret (created_at ":" 2020-06-27T14: 16: 42Z). Creation date is not 8 Jan 2020 as he faked in the commits (https://github.com/soxoj/maigret/commit/ac0be37480dc0e90b5bd08f789acaf8b717a9a98).
Here is his forked real repository https://github.com/torerobo/maigret (he illegally used the Snoop Project database). He is not allowed to distribute his pirated work under the MIT license (because he illegally used the Snoop Project database).

Some evidence of his piracy (I collected a lot of them, for example, I dumped and hashed all the chats in Telegram, where he wrote, about Snoop and his illegal actions, all this evidence will go to court against the pirate):
https://www.youtube.com/watch?v=R8dWfbyKSsE&feature=youtu.be
https://www.youtube.com/watch?v=Z_titGNXm6g
Here at 18 seconds, you can see that this is a fork of Sherlock (before he started obfuscating the repository).
https://www.youtube.com/watch?v=9FCfpG75YAc

I ask you not to encourage piracy and to block the pirate repository maigret:
https://github.com/jivoi/awesome-osint/pull/199

UPD: Часть [доказательств в PDF](https://drive.google.com/file/d/1-O5TYmgt9xarFCg0oSOitt4ZjJm8M_yR/view) формате/RU

**Comment by JoYMnk** [comment]
5pasib0
