### ISSUE TITLE
Refine list summary / mission statement.

### ISSUE THREAD

**Issue by quinnr** [jivoi/awesome-osint#275]
Going through and reviewing for links that are not very useful and I think that this list could benefit from refining the summary a bit to add focus. "Open source intelligence"/OSINT is a very amorphous term, but there is probably at least some improvement to be made to the current description: 
> A curated list of amazingly awesome open source intelligence tools and resources. [Open-source intelligence (OSINT)](https://en.wikipedia.org/wiki/Open-source_intelligence) is intelligence collected from publicly available sources. In the intelligence community (IC), the term "open" refers to overt, publicly available sources (as opposed to covert or clandestine sources) 

I think about OSINT in general terms of using information available from publicly accessible websites, tools, or databases in order to gather and congregate information with real-world applications. 

Even with a broad definition I think there's room to focus the list a bit. There are pages of translation apps and it's not clear what utility that provides over just one tool that is curated as being the best for curation. The clutter makes it difficult to navigate!

**Comment by eneller** [comment]
Even without improving the OSINT description, i think there is a point to be made that this list has become a little bloated, like:
- Pastebins: In my opinion, the pastebin section should contain tools for analyzing / searching / scraping pastebins, not a list of pastebins that just _exist_.
- Translation, this should really be located and linked to in [awesome-translations/tools](https://github.com/mbiesiad/awesome-translations#tools)
- probably more

**Comment by spmedia** [comment]
@quinnr and @eneller , I agree. there is some bloat here for sections kinda unrelated to OSINT.

translation section removed and linked to Awesome Translations , see #423 

what other sections are y'all thinking about in terms of bloat/unrelated?

Cheers

**Comment by Lissy93** [comment]
Came here to say something similar. There's a lot of very valuable content here, but the excess fluff makes it harder to find the useful services.

For reference, most of what was added in commit 4ab36f929a042379fd64b8ce89e52ecf3ca3bcaa and 937e65559edd0a93e3c9970c37ca9f28f99b5fa3 has no relation to OSINT.

---

I went through the list properly this evening, and identified the following sections as candidates for deletion (not to say that the tools are not useful or valuable, just that they'd be better placed elsewhere).

<details>

<summary>Sections unrelated to OSINT</summary>

In the readme, it's broadly [**this selection**](https://github.com/jivoi/awesome-osint/blob/13cfc8e48d130d0f15f974d7b71210908b4dfdc2/README.md?plain=1#L790-L1889C14) which is mostly fluff, and includes the following sections:
- [Stock Images](https://github.com/jivoi/awesome-osint#-stock-images)
- [News](https://github.com/jivoi/awesome-osint#-news)
- [Bookmarking](https://github.com/jivoi/awesome-osint#-bookmarking)
- [Startpages](https://github.com/jivoi/awesome-osint#-startpages)
- [Browsers](https://github.com/jivoi/awesome-osint#-browsers)
- [Note-taking](https://github.com/jivoi/awesome-osint#-note-taking)
- [Annotation Tools](https://github.com/jivoi/awesome-osint#-annotation-tools)
- [Writing and Office Tools](https://github.com/jivoi/awesome-osint#-writing-and-office-tools)
- [Slide Show and Presentation Tools](https://github.com/jivoi/awesome-osint#-slide-show-and-presentation-tools)
- [Digital Publishing](https://github.com/jivoi/awesome-osint#-digital-publishing)
- [Newsletter Tools](https://github.com/jivoi/awesome-osint#-newsletter-tools)
- [Digital Storytelling](https://github.com/jivoi/awesome-osint#-digital-storytelling)
- [Infographics and Data Visualization](https://github.com/jivoi/awesome-osint#-infographics-and-data-visualization)
- [Image and Photo Editing](https://github.com/jivoi/awesome-osint#-image-and-photo-editing)
- [Productivity Tools](https://github.com/jivoi/awesome-osint#-productivity-tools)
- [E-mail Management](https://github.com/jivoi/awesome-osint#-e-mail-management)
- [Document and Reference Management](https://github.com/jivoi/awesome-osint#-document-and-reference-management)
- [PDF Management](https://github.com/jivoi/awesome-osint#-pdf-management)
- [OCR Tools](https://github.com/jivoi/awesome-osint#-ocr-tools)
- [Cloud Storage and File Sharing](https://github.com/jivoi/awesome-osint#-cloud-storage-and-file-sharing)
- [Web Automation](https://github.com/jivoi/awesome-osint#-web-automation)
- [Dashboard Tools](https://github.com/jivoi/awesome-osint#-dashboard-tools)
- [Wikis](https://github.com/jivoi/awesome-osint#-wikis)
- [Collaboration and Project Management](https://github.com/jivoi/awesome-osint#-collaboration-and-project-management)
- [Communication Tools](https://github.com/jivoi/awesome-osint#-communication-tools)
- [Calendars and Scheduling](https://github.com/jivoi/awesome-osint#-calendars-and-scheduling)
- [Mind Mapping, Concept Mapping and Idea Generation Tools](https://github.com/jivoi/awesome-osint#-mind-mapping-concept-mapping-and-idea-generation-tools)

</details>

Take for example the [Startpages](https://github.com/jivoi/awesome-osint#-startpages) section, if I were looking for a startpage, this is not where I'd expect to find it, especially as the recommendations includes is sites like  http://konvergens.dk/zcom/ which hasn't been updates for 14 years (I have a [better startpage](https://github.com/lissy93/dashy) - shameless plug! 😉)

**Comment by spmedia** [comment]
It has been revamped <3
