### ISSUE TITLE
Add Datalux/Osintgram to list

### ISSUE THREAD

**Issue by quinnr** [jivoi/awesome-osint#278]
[Osintgram](https://github.com/Datalux/Osintgram) seems like a good fit for this list. Spotted in some online news coverage this week. 

Docker image tool that supports some pretty rad OSINT procedures on any public Instagram handle, including: 

> - addrs           Get all registered addressed by target photos
> - captions        Get user's photos captions
> - comments        Get total comments of target's posts
> - followers       Get target followers
> - followings      Get users followed by target
> - fwersemail      Get email of target followers
> - fwingsemail     Get email of users followed by target
> - fwersnumber     Get phone number of target followers
> - fwingsnumber    Get phone number of users followed by target
> - hashtags        Get hashtags used by target
> - info            Get target info
> - likes           Get total likes of target's posts
> - mediatype       Get user's posts type (photo or video)
> - photodes        Get description of target's photos
> - photos          Download user's photos in output folder
> - propic          Download user's profile picture
> - stories         Download user's stories  
> - tagged          Get list of users tagged by target
> - wcommented      Get a list of user who commented target's photos
> - wtagged         Get a list of user who tagged target

I'll put a PR together with a description when I have time.

**Comment by spmedia** [comment]
Added Osintgram in #287 

Thank you!
