### ISSUE TITLE
A few websites to add:

### ISSUE THREAD

**Issue by cyb3rspace** [jivoi/awesome-osint#297]
filmot.com - Search all youtube subtitles
haveibeenzuckered.com - Check if a phone number appeared in a Facebook data leak

**Comment by michealcharles** [comment]
**[Trends Twitter](https://trendstwitter.com/)** is a platform from where you can get all the new topics & Hash tags about Twitter World wide.

**Comment by spmedia** [comment]
Thanks

Added in #299
