### ISSUE TITLE
Need to update

### ISSUE THREAD

**Issue by DenverDaveH** [jivoi/awesome-osint#353]
Hello,
This is an incredibly awesome list of resources. And as large as it is, somethings change. For instance:

http://www.reversegenie.com/email.php 

now translates to

https://www.reversephonecheck.com/

You may want to consider dropping it. Or modify as you see fit.

Thanks again!
Dave

**Comment by spmedia** [comment]
Dave,

Feel free to do a pull request and make whatever changes.
