### ISSUE TITLE
Some changes need to get added to master Awesome list

### ISSUE THREAD

**Issue by spmedia** [jivoi/awesome-osint#38]
Hey @jivoi ,

https://github.com/sindresorhus/awesome/pull/983

I made the request here but there a few changes that need to be made to the overall list.

Care to add me as an admin maintainer so I can tidy up list a bit and get us approved?

Thanks

**Comment by jivoi** [comment]
Hey @spmedia.
Thank you for your help.
I added to you a push access to this repository.
Check it out =)
