### ISSUE TITLE
Add tools: MetaGer and searx

### ISSUE THREAD

**Issue by js-on** [jivoi/awesome-osint#385]
Two tools worth to mention in this list.

**MetaGer:**
> MetaGer is one of the oldest meta search engines, developed at the university in Hanover in the late 90s. It's known for high privacy / security standards, transparency and good search results from many different underlaying search engines.

[MetaGer](https://metager.de/)

[Source Code](https://gitlab.metager.de/open-source/MetaGer/-/tree/development/)

**searx**
> Searx is a free internet metasearch engine which aggregates results from more than 70 search services. Users are neither tracked nor profiled. Additionally, searx can be used over Tor for online anonymity.

[Docs](https://searx.github.io/searx/)

[Public instances](https://searx.space/)

[Source Code](https://github.com/searx/searx)

**Comment by virtadpt** [comment]
+1 for Searx.  Long time user for OSINT research and it's my go-to every day.

**Comment by spmedia** [comment]
open this as a pr, not an issue.
