### ISSUE TITLE
Removing allexperts.com

### ISSUE THREAD

**Issue by yansenapdwyll** [jivoi/awesome-osint#47]
After more than 19 years, and over two million questions answered, AllExperts.com is now closed. We apologize for any inconvenience.

You can find our latest Expert-answered content at Thoughtco.com.

**Comment by IsabelleJ84** [comment]
Where can old topics be founds, I'm looking for all commentaries from Clifford Readout.  Please?

**Comment by spmedia** [comment]
I'm not sure this is the proper place to discuss this but you could use the Wayback Machine maybe?

https://web.archive.org/web/*/allexperts.com
