### ISSUE TITLE
[IDEA] Add the Amass subdomain enumeration tool

### ISSUE THREAD

**Issue by caffix** [jivoi/awesome-osint#64]
The Amass tool is similar to TheHarvester in that it is a DNS OSINT tool. It would be great to have it on your list. The link to the project page is below:

https://github.com/caffix/amass

Thanks in advance!

**Comment by spmedia** [comment]
Very cool tool @caffix . I will play with it today.

Added @ https://github.com/jivoi/awesome-osint/pull/65

**Comment by caffix** [comment]
Thanks, @spmedia!
