### ISSUE TITLE
Latest iIntelligence OSINT Handbook 2018 released

### ISSUE THREAD

**Issue by ABAUK** [jivoi/awesome-osint#77]
Hi everyone, the latest iIntelligence OSINT Handbook 2018 has just been released.  How can we extract the data into your excellent GitHub format?  Happy to help if needed.  

https://www.i-intelligence.eu/wp-content/uploads/2018/06/OSINT_Handbook_June-2018_Final.pdf

**Comment by spmedia** [comment]
Hey @ABAUK ,

You could fork the repo and then manually copy everything from the PDF into the fork.

It would also be nice to get a link to our Awesome OSINT list in your PDF :)

**Comment by ABAUK** [comment]
Hi Jivoli

I include a link to your fabulous Github resource on this page

Would you like me to change wording or promote your link more

Andy
