### ISSUE TITLE
Check for low-quality links

### ISSUE THREAD

**Issue by fosslinux** [jivoi/awesome-osint#80]
Each section needs to be checked for low quality links that:
a) are not awesome
b) low-quality
c) very little information
d) removed/dead link

Do this in sections:
- [x] General Search
- [x] Main National Search Engines
- [x] Meta Search
- [x] Specialty Search Engines
- [x] Visual Search and Clustering Search Engines
- [x] Similar Sites Search
- [x] Document and Slides Search
- [x] Pastebins
- [x] Code Search
- [x] Major Social Networks
- [x] Real-Time Search, Social Media Search, and General Social Media Tools
- [x] Social Media Tools/Twitter
- [x] Social Media Tools/Facebook
- [x] Social Media Tools/Google+
- [x] Social Media Tools/Instagram
- [x] Social Media Tools/Pinterest
- [x] Social Media Tools/Reddit
- [x] Social Media Tools/VKontakte
- [x] Social Media Tools/Tumblr
- [x] Social Media Tools/LinkedIn
- [x] Blog Search
- [x] Forums and Discussion Boards Search
- [x] Username Check
- [x] People Investigations
- [x] E-mail Search / E-mail Check
- [x] Phone Number Research
- [x] Expert Search
- [x] Company Research
- [x] Job Search Resources
- [x] Q&A Sites
- [ ] Domain and IP Research
- [ ] Keywords Discovery and Research
- [ ] Web History and Website Capture
- [ ] Language Tools
- [ ] Image Search
- [ ] Image Analysis
- [ ] Stock Images
- [ ] Video Search and Other Video Tools
- [ ] Radio and Podcasts Tools
- [ ] Academic Resources and Grey Literature
- [ ] Books and Reading
- [ ] Geospatial Research and Mapping Tools
- [ ] News
- [ ] News Digest and Discovery Tools
- [ ] Fact Checking
- [ ] Data and Statistics
- [ ] Web Monitoring
- [ ] Bookmarking
- [ ] Startpages
- [ ] Browsers
- [ ] Offline Browsing
- [x] VPN Services
- [ ] Note-taking
- [ ] Annotation Tools
- [ ] Writing and Office Tools
- [ ] Slide Show and Presentation Tools
- [ ] Digital Publishing
- [ ] Newsletter Tools
- [ ] Digital Storytelling
- [ ] Infographics and Data Visualization
- [ ] Image and Photo Editing
- [ ] Productivity Tools
- [ ] E-mail Management
- [ ] Document and Reference Management
- [ ] PDF Management
- [ ] OCR Tools
- [ ] Cloud Storage and File Sharing
- [ ] Web Automation
- [ ] Dashboard Tools
- [ ] Wikis
- [ ] Collaboration and Project Management
- [ ] Communication Tools
- [ ] Calendars and Scheduling
- [ ] Mind Mapping, Concept Mapping and Idea Generation Tools
- [ ] Social Network Analysis
- [x] Privacy and Encryption Tools
- [x] DNS
- [x] Other Tools
- [x] OSINT Videos

Also see #79 for more to do.

**Comment by 0xRecon** [comment]
FYI. **Mapbuildr** has dead link as of today.
"Domain not found"

**Comment by PZiwey** [comment]
i marked some dead links in Twitter Area, or should i delete them instead of marking

**Comment by morristhepredator** [comment]
Could anyone add https://www.projoodle.com to the "Productivity Tools" section? It's a free todo list tool

**Comment by quinnr** [comment]
#274 proposes removing "Battle of the Internet Giants" as it does not seem like a useful source/I couldn't find information that would be useful to refer to regularly on the page.

**Comment by quinnr** [comment]
See #285 removing 129 links, 127 defunct and 2 not open, and fixing 2 broken links.

**Comment by Headedbranch225** [comment]
canthide.me is dead
