### ISSUE TITLE
Please consider adding REScure Threat Intel Feed

### ISSUE THREAD

**Issue by eshanaswar** [jivoi/awesome-osint#86]
Nice list. We have started a new malware threat feed (REScure) which is accessible at :

`homepage : https://rescure.fruxlabs.com/`
`Feedpath : https://rescure.fruxlabs.com/rescure_blacklist.txt`

The feed is curated form an inhouse threat intelligence solution and is updated at every 6 hours. A blogpost detailing about this is mentioned here :

`https://www.theprohack.com/2018/09/rescure-cyber-threat-intelligence-feed.html`

Currently limited to only malicious IPs, we will enhance this by adding IoCs such as malware hashes, domains et al in future.

Thanks !

**Comment by spmedia** [comment]
Added in latest update. Thanks!
